# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egressapp', '0004_autorizacaoaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacaoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egressapp.Turma')),
            ],
        ),
    ]
