# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egressapp', '0005_autorizacaoturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacaoaluno',
            name='ultilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autorizacaoturma',
            name='ultilizado',
            field=models.BooleanField(default=False),
        ),
    ]
