# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egressapp', '0006_auto_20171229_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacaoaluno',
            name='ultilizado',
        ),
        migrations.RemoveField(
            model_name='autorizacaoturma',
            name='ultilizado',
        ),
    ]
