# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egressapp', '0009_auto_20180108_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
