# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egressapp', '0010_auto_20180108_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='crudAluno',
            new_name='gerenciar_Alunos',
        ),
        migrations.AddField(
            model_name='perfil',
            name='gerenciar_Autorizacao_Alunos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='gerenciar_Autorizacao_Turmas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='gerenciar_Estatistica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='gerenciar_Liberacao_Alunos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='gerenciar_Permissoes_Usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='gerenciar_Turmas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='gerenciar_Usuarios',
            field=models.BooleanField(default=False),
        ),
    ]
