# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egressapp', '0011_auto_20180108_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='gerenciar_Estatistica',
            new_name='gerenciar_Relatorios',
        ),
    ]
